apiVersion: skaffold/v1beta2
kind: Config
build:
  local: 
    push: false # skaffold by default will try to push always to dockerhub. Set it to false so doesn#'t push any local change before testing
  artifacts:
    - image: hoesslj/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': . # If find js file change, copy it to container
        '**/*.css': . # If find js file change, copy it to container
        '**/*.html': . # If find js file change, copy it to container
        # If any other file is changed, will revert back to mode 1
    - image: hoesslj/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*js': .
    - image: hoesslj/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*js': .
deploy:
  kubectl:
    manifests: # List the different config files we want to monitor
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/client-cluster-ip-service.yaml